- name: add Pulse audio equalizer repository
  apt_repository: repo='deb http://ppa.launchpad.net/nilarimogard/webupd8/ubuntu trusty main'
  become: yes

- name: install pulse audio equalizer
  apt:
    name: pulseaudio-equalizer
    state: latest
  become: yes
